Feature/fix for circle (#2)
mojaloop/forensic-logging-client pull request #3
Opened 2017-12-13 12:42 UTC by mdebarros

* Updated for open source repos

* Added public access to the npm publish command

2017-12-20 21:51 UTC, BillHodghead requested changes
I hate to say this, but Jfrog finally got back to us and we now have a publicly accessible repo at https://mojaloop.jfrog.io/ See the doc in Mojaloop Admin in Dropbox for CircleCI info

2017-12-21 11:36 UTC, mdebarros commented
@bhcrosslake What is the issue using npmjs.com? 

We currently are already using it. I see no benefit in switching back.

I say we continue with npmjs.com.

2017-12-28 20:24 UTC, bhcrosslake commented
OK, let's merge this using NPM now. We can refactor later to JFrog.

2017-12-28 20:24 UTC, BillHodghead approved these changes

2017-12-28 20:24 UTC, merged